"""
Django settings for HN_Transporte project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2*3m%awqb#dvhycw5-9zr7t^*z7@d9^h$h9kvo+j#nz!aln8)u'

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

DEBUG = os.environ.get('DEBUG', True)
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'dj_rest_auth.registration',
    'corsheaders',
    'django_filters',
    'drf_yasg', #for swagger 
    'HN_Transporte_api',
]

AUTHENTICATION_BACKENDS = [

    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',

]

CORS_ORIGIN_ALLOW_ALL = True 

AUTH_USER_MODEL = "HN_Transporte_api.User"

ACCOUNT_EMAIL_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'username'
ACCOUNT_EMAIL_VERIFICATION = 'none'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'dj_rest_auth.jwt_auth.JWTCookieAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DATETIME_FORMAT': "%d-%m-%Y %H:%M:%S",
    "DATE_FORMAT": "%d-%m-%Y",
    "DATE_INPUT_FORMATS" : [
            "%d-%m-%Y",  # '25-10-2006'
            "%Y-%m-%d",  # '2006-10-25'
            "%m/%d/%Y",  # '10/25/2006'
            "%m/%d/%y",  # '10/25/06'
            "%b %d %Y",  # 'Oct 25 2006'
            "%b %d, %Y", # 'Oct 25, 2006'
            "%d %b %Y",  # '25 Oct 2006'
            "%d %b, %Y", # '25 Oct, 2006'
            "%B %d %Y",  # 'October 25 2006'
            "%B %d, %Y", # 'October 25, 2006'
            "%d %B %Y",  # '25 October 2006'
            "%d %B, %Y", # '25 October, 2006'
    ],
    "DEFAULT_PAGINATION_CLASS": 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10
}

REST_AUTH = {
    'REGISTER_SERIALIZER': 'HN_Transporte_api.utils.rest_auth_serializers.RegisterSerializer',
    'REGISTER_PERMISSION_CLASSES': ('rest_framework.permissions.AllowAny',),
    'OLD_PASSWORD_FIELD_ENABLED' : True,
    'LOGOUT_ON_PASSWORD_CHANGE' : True,
    'USE_JWT': True,
    "JWT_AUTH_HTTPONLY": False,
    'JWT_SERIALIZER': 'HN_Transporte_api.utils.rest_auth_serializers.JWTSerializer',
    'JWT_TOKEN_CLAIMS_SERIALIZER': 'HN_Transporte_api.utils.rest_auth_serializers.MyTokenObtainSlidingSerializer',
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=12),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'HN_Transporte.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'HN_Transporte.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases



# DATABASES = {
   
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'resultasonlinech_elvethe',
#         'USER':  os.environ.get("SQL_USER", 'resultasonlinech_chme'), 
#          'PASSWORD': os.environ.get("SQL_PASSWORD", 'H6[o6k6u+KT7'),
#         'HOST': os.environ.get("SQL_HOST", '104.219.251.242'), 
#         'PORT': os.environ.get("SQL_PORT", '3306'),
           
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
