# Generated by Django 4.1.7 on 2024-12-07 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HN_Transporte_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 12, 7, 14, 59, 56, 238878, tzinfo=datetime.timezone.utc), verbose_name='Operation Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('Dépôt', 'Dépôt'), ('Débit', 'Débit'), ('other', 'Autre')], max_length=20),
        ),
    ]
