# Generated by Django 4.1.7 on 2024-12-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HN_Transporte_api', '0002_operation_date_alter_operation_operation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='facteur_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
