# Generated by Django 4.1.7 on 2024-12-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HN_Transporte_api', '0003_operation_facteur_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=40, null=True)),
                ('statu', models.BooleanField(default=True)),
            ],
        ),
    ]
