# Generated by Django 4.1.7 on 2024-12-08 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HN_Transporte_api', '0004_chauffeur'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chauffeur',
            old_name='statu',
            new_name='statut',
        ),
    ]
