# Generated by Django 4.1.7 on 2024-12-08 02:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HN_Transporte_api', '0005_rename_statu_chauffeur_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
