# Generated by Django 4.1.7 on 2024-12-08 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HN_Transporte_api', '0006_chauffeur_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('volume', models.FloatField()),
                ('disponibilite', models.BooleanField(default=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contrat', models.CharField(max_length=255)),
                ('volume', models.FloatField()),
                ('nbre_voyages', models.IntegerField()),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=10)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HN_Transporte_api.camion')),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HN_Transporte_api.chauffeur')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
