# Generated by Django 4.1.7 on 2024-12-08 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HN_Transporte_api', '0007_camion_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 8, 8, 38, 13, 276672, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
