# Generated by Django 4.1.7 on 2024-12-08 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HN_Transporte_api', '0008_facture_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HN_Transporte_api.client'),
        ),
    ]
