# Generated by Django 4.1.7 on 2024-12-13 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HN_Transporte_api', '0009_facture_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='payment_type',
            field=models.CharField(choices=[('Paiement_Espèce', 'Paiement Espèce'), ('Paiement_Digital', 'Paiement Digital'), ('other', 'Autre')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facture',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
