# Generated by Django 4.1.7 on 2024-12-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HN_Transporte_api', '0010_operation_payment_type_alter_facture_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Paiement_Espèce', 'Paiement Espèce'), ('Paiement_Digital', 'Paiement Digital'), ('other', 'Autre')], max_length=20, null=True),
        ),
    ]
