# Generated by Django 4.1.7 on 2024-12-20 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HN_Transporte_api', '0012_alter_operation_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepenseCamion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_depense', models.DateField(auto_now_add=True)),
                ('type_depense', models.CharField(choices=[('Carburant', 'Carburant'), ('Entretien', 'Entretien'), ('Réparation', 'Réparation'), ('Autre', 'Autre')], default='Autre', max_length=50)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='HN_Transporte_api.camion')),
            ],
        ),
    ]
