# Generated by Django 4.1.7 on 2024-12-20 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HN_Transporte_api', '0014_depensecamion_responsable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depensecamion',
            old_name='date_depense',
            new_name='date',
        ),
    ]
