# Generated by Django 4.1.7 on 2024-12-21 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HN_Transporte_api', '0015_rename_date_depense_depensecamion_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depensecamion',
            old_name='montant',
            new_name='amount',
        ),
    ]
