# Generated by Django 4.1.7 on 2024-12-22 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HN_Transporte_api', '0016_rename_montant_depensecamion_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='salaire_defaut',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=10),
        ),
        migrations.CreateModel(
            name='SalaireChauffeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveIntegerField()),
                ('annee', models.PositiveIntegerField()),
                ('salaire_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avances', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaires', to='HN_Transporte_api.chauffeur')),
            ],
            options={
                'unique_together': {('chauffeur', 'mois', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='HistoriqueAvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('salaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avances_historique', to='HN_Transporte_api.salairechauffeur')),
            ],
        ),
    ]
